### PR TITLE
add support for also_private

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by autarch** [comment]
This looks good, but can you also add an entry to Changes?

**Comment by dagolden** [comment]
Done, squashed and force pushed.

**Comment by autarch** [comment]
I ended up merging this from the CLI with a few wording tweaks. Thanks!

**Comment by dagolden** [comment]
Thanks!

Could you please release it to CPAN when you have a chance so I can start using it? :-)

**Comment by autarch** [comment]
Done. I started the release yesterday and apparently got distracted.

**Pull request closed without merging**
